export const product = [
  {
    id: 1,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 2,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 3,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 4,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 5,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 6,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },

  {
    id: 7,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "70%",
    type: "flash",
  },
  {
    id: 8,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 9,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 10,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "30%",
    type: "flash",
  },
  {
    id: 11,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 12,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "40%",
    type: "flash",
  },
  {
    id: 13,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 14,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "50%",
    type: "flash",
  },
  {
    id: 15,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 16,
    image: "",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
];

export const category = [
  {
    id: 1,
    image: "",
    name: "Phone & Tablets",
    category: true,
  },
  {
    id: 2,
    image: "",
    name: "Computers & Accessories",
    category: true,
  },
  {
    id: 3,
    image: "",
    name: "Men’s Clothing",
    category: true,
  },
  {
    id: 4,
    image: "",
    name: "Shoes",
    category: true,
  },
  {
    id: 5,
    image: "",
    name: "Mobile Accessories",
    category: true,
  },
  {
    id: 6,
    image: "",
    name: "Automotive and Tools",
    category: true,
  },
  {
    id: 7,
    image: "",
    name: "Beauty and Personal Care",
    category: true,
  },
  {
    id: 8,
    image: "",
    name: "Books and Stationery",
    category: true,
  },
  {
    id: 9,
    image: "",
    name: "Clothing and Fashion",
    category: true,
  },
  {
    id: 10,
    image: "",
    name: "Electronics",
    category: true,
  },
  {
    id: 11,
    image: "",
    name: "Health and Wellness",
    category: true,
  },
  {
    id: 12,
    image: "",
    name: "Home and Living",
    category: true,
  },
  {
    id: 13,
    image: "",
    name: "Pets and Pet Supplies",
    category: true,
  },
  {
    id: 14,
    image: "",
    name: "Sports and Outdoors",
    category: true,
  },
  {
    id: 15,
    image: "",
    name: "Toys and Games",
    category: true,
  },
];
